from pymongo import MongoClient
client=MongoClient("mongodb+srv://test:test@cluster0.nvu4g.mongodb.net/myFirstDatabase?retryWrites=true&w=majority")
db=client.get_database('song_db')
# print(db)
records=db.song_records

records.insert(
    [{'name': 'tum hi ho', 'emotion': 'LOVE', 'link': 'https://www.youtube.com/embed//IJq0yyWug1k'}, {'name': 'ek ladki ko dekha toh aisa laga', 'emotion': 'LOVE', 'link': 'https://www.youtube.com/embed//XKbiIahG6ok'}, {'name': 'love me thoda aur', 'emotion': 'LOVE', 'link': 'https://www.youtube.com/embed//lz1-1Q8Gync'}, {'name': 'raanjhana', 'emotion': 'LOVE', 'link': 'https://www.youtube.com/embed//UPEU5HT9fzA'}, {'name': 'kalank', 'emotion': 'LOVE', 'link': 'https://www.youtube.com/embed//Grr0FlC8SQA'}, {'name': 'ajab si', 'emotion': 'LOVE', 'link': 'https://www.youtube.com/embed//bdS6OoH1W2A'}, {'name': 'tu jaane na', 'emotion': 'LOVE', 'link': 'https://www.youtube.com/embed//P8PWN1OmZOA'}, {'name': 'dhokadhadi', 'emotion': 'LOVE', 'link': 'https://www.youtube.com/embed//hrcICKdEkYQ'}, {'name': 'sajda', 'emotion': 'LOVE', 'link': 'https://www.youtube.com/embed//3rPEWcY6Oww'}, {'name': 'tum tak', 'emotion': 'LOVE', 'link': 'https://www.youtube.com/embed//k09uvR5eUao'}, {'name': 'jaise mera tu', 'emotion': 'LOVE', 'link': 'https://www.youtube.com/embed//8HfXXnTo3wI'}, {'name': 'rang jo laagyo re', 'emotion': 'LOVE', 'link': 'https://www.youtube.com/embed//zRaoAWEY9Jo'}, {'name': 'piya o re piya', 'emotion': 'LOVE', 'link': 'https://www.youtube.com/embed//u-FaTNxrWhw'}, {'name': 'oh sathi', 'emotion': 'LOVE', 'link': 'https://www.youtube.com/embed//YuXLN23ZGQo'}, {'name': 'qaafirana', 'emotion': 
'LOVE', 'link': 'https://www.youtube.com/embed//ZmcBC9-wAXM'}, {'name': 'tera ban jaunga', 'emotion': 'LOVE', 'link': 'https://www.youtube.com/embed//Qdz5n1Xe5Qo'}, {'name': 'kinna sona', 'emotion': 'LOVE', 'link': 'https://www.youtube.com/embed//5qIJ7tQ2QbM'}, {'name': 'main rahun ya na rahun', 'emotion': 'LOVE', 'link': 'https://www.youtube.com/embed//Dp6lbdoprZ0'}, {'name': 'tune jo na kahan', 'emotion': 'LOVE', 'link': 'https://www.youtube.com/embed//dTu5dTEzVM4'}, {'name': 'bekhayli', 'emotion': 'LOVE', 'link': 'https://www.youtube.com/embed//VOLKJJvfAbg'}, {'name': 'vaaste', 'emotion': 'LOVE', 'link': 'https://www.youtube.com/embed//BBAyRBTfsOU'}, {'name': 'o saathi', 'emotion': 'LOVE', 'link': 'https://www.youtube.com/embed//YuXLN23ZGQo'}, {'name': 'perfect', 'emotion': 'LOVE', 'link': 'https://www.youtube.com/embed//2Vv-BfVoq4g'}, {'name': 'you are the reason', 'emotion': 'LOVE', 'link': 'https://www.youtube.com/embed//ShZ978fBl6Y'}, {'name': 'love me like you do', 'emotion': 'LOVE', 'link': 'https://www.youtube.com/embed//AJtDXIazrMo'}]
)
print(records.count_documents({}))
